name: ia-rug
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::dask-ec2=0.3.0=py36_0
- conda-forge::feather-format=0.4.0=py36_2
- conda-forge::ipython=6.1.0=py36_0
- conda-forge::jupyter=1.0.0=py36_0
- conda-forge::matplotlib=2.0.2=np112py36_0
- conda-forge::notebook=5.0.0=py36_0
- conda-forge::numpy=1.12.1=py36_blas_openblas_200
- conda-forge::pandas=0.20.1=np112py36_0
- conda-forge::pandas-datareader=0.4.0=py36_0
- conda-forge::patsy=0.4.1=py36_0
- conda-forge::pip=9.0.1=py36_0
- conda-forge::plotnine=0.2.0=py36_0
- conda-forge::python=3.6.1=3
- conda-forge::rpy2=2.8.5=py36r3.3.2_0
- conda-forge::scikit-learn=0.18.1=np112py36_blas_openblas_200
- conda-forge::scipy=0.19.0=np112py36_blas_openblas_200
- conda-forge::seaborn=0.7.1=py36_0
- conda-forge::setuptools=33.1.1=py36_0
- conda-forge::statsmodels=0.8.0=np112py36_0
- conda-forge::wheel=0.29.0=py36_0
